CREATE DATABASE IF NOT EXISTS burgers_db;

USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers(

	id INT(11) AUTO_INCREMENT NOT NULL, 
	burger_name VARCHAR(225) NOT NULL, 
	devoured BOOLEAN NOT NULL DEFAULT FALSE, 
	date TIMESTAMP NOT NULL, 
	PRIMARY KEY(id) );